title: The Hexagon Games
description: Board, card, and video games by The Hexagon Games.
author: The Hexagon Games
logo: https://thehexagongames.com/uploaded-files/all/hex_logo.png
github: https://github.com/MillerHollinger
about: Games

allowsearch: false
plugins:
  - jekyll-feed
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: false


disqus_shortname:
google_analytics:

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
